### ISSUE TITLE
Build failure on WORKING commit

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [Haremun/IsThisBoardLegal#1]
Tests cannot pass:
```
Board parser test
java.io.FileNotFoundException: /home/tammo/Kod/Akademia/egzaminWst%C4%99pny/IsThisBoardLegal_KamilBiega%C5%84ski/target/classes/bad_board.txt (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at com.bieganski.board.BoardReader.readFileToList(BoardReader.java:22)
	at com.bieganski.BoardParserTest.parse_WrongLettersInFile(BoardParserTest.java:25)
[...]
[ERROR] Failures: 
[ERROR]   BoardParserTest.parse_WrongLettersInFile » Test 
Method BoardParserTest.parse_...
[INFO] 
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.247 s
[INFO] Finished at: 2019-11-16T20:21:20+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project is-this-board-legal: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/tammo/Kod/Akademia/egzaminWstępny/IsThisBoardLegal_KamilBiegański/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
```

**Comment by LIttleAncientForestKami** [comment]
Fixed. Closing.
