### ISSUE TITLE
JAR without manifest

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [Haremun/IsThisBoardLegal#2]
JAR cannot be executed due to manifest troubles.

After #1 I ran without tests, this made packaging successful. However run fails like so:

```
[tammo@lafk-T470 IsThisBoardLegal_KamilBiegański]$ java -jar target/is-this-board-legal-1.0-SNAPSHOT.jar                                                                                                  [INSERT]
no main manifest attribute, in target/is-this-board-legal-1.0-SNAPSHOT.jar
```

**Comment by LIttleAncientForestKami** [comment]
JAR works and launches, but fails with NPE right after:

---
[tammo@lafk-T470 IsThisBoardLegal_KamilBiegański]$ java -jar target/is-this-board-legal-1.0-SNAPSHOT.jar                                                                                                  [INSERT]
java.io.FileNotFoundException: file:/home/tammo/Kod/Akademia/egzaminWst%c4%99pny/IsThisBoardLegal_KamilBiega%c5%84ski/target/is-this-board-legal-1.0-SNAPSHOT.jar!/board.txt (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at com.bieganski.board.BoardReader.readFileToList(BoardReader.java:22)
	at com.bieganski.App.main(App.java:15)
Exception in thread "main" java.lang.NullPointerException
	at com.bieganski.board.Board.toString(Board.java:43)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	at com.bieganski.App.main(App.java:19)
---

**Comment by LIttleAncientForestKami** [comment]
I have a fix :)
